### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by mnot** [martinthomson/http-replay#2]
It'd be nice if we could find a way to couch this as applying to not only TLS, but also QUIC and TFO.

**Comment by wtarreau** [comment]
It's a good point, what blocks me from enabling TFO to the server in haproxy is that I'm not able to replay. With such a signal form the client I'd happily enable it. What is needed is to ensure someone in the chain says "do not hesitate to take risks going faster, I'll recover if something bad happens". I was thinking that we probably didn't need the early-data header because 0RTT was good enough a signal but in the end maybe we need a more generic "Retryable: ok" header field. We need to be careful not to design too broadly though or it will never end :-/

**Comment by martinthomson** [comment]
I'm not especially concerned about TFO here.  An attacker can generate a replay attack trivially if we don't have TLS, so that reduces to the protections in TLS.

QUIC definitely qualifies.
